// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5nZ55kwC04RyhEQ8lgFPZqn4wb4LoXxg',
    appId: '1:210496758992:web:18b61d72f5eef00b2f6ad5',
    messagingSenderId: '210496758992',
    projectId: 'chat-online-810a2',
    authDomain: 'chat-online-810a2.firebaseapp.com',
    storageBucket: 'chat-online-810a2.appspot.com',
    measurementId: 'G-80WD498FHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEuZdiZcYyNFeGLKfS_koReYH7Nay-kLo',
    appId: '1:210496758992:android:12d65df00f686c942f6ad5',
    messagingSenderId: '210496758992',
    projectId: 'chat-online-810a2',
    storageBucket: 'chat-online-810a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlzV9L3DwdHH11ddpr0JEFI_Alyd4S4mo',
    appId: '1:210496758992:ios:443fc5fb26bf8de72f6ad5',
    messagingSenderId: '210496758992',
    projectId: 'chat-online-810a2',
    storageBucket: 'chat-online-810a2.appspot.com',
    iosClientId: '210496758992-mjceuhiqnimi438cgi36qc59tm4e5g4b.apps.googleusercontent.com',
    iosBundleId: 'com.leandroadal.chatOnline',
  );

}